# Generated by Django 4.0.4 on 2022-07-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tag_article_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag_slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
